module.exports = {
  collectCoverageFrom: [
    '<rootDir>/src/**/*.js',
    '<rootDir>/src/**/*.ts',
  ],
  coveragePathIgnorePatterns: [
    '<rootDir>/src/parser/grammars/(generate|grammar).js',
  ],
  moduleNameMapper: {
    '^\\./ComparePoint\\.js$': '<rootDir>/src/ComparePoint.ts',
    '^\\.\\./ComparePoint\\.js$': '<rootDir>/src/ComparePoint.ts',
    '^\\.\\./\\.\\./ComparePoint\\.js$': '<rootDir>/src/ComparePoint.ts',
    '^\\.\\./\\.\\./src/ComparePoint\\.js$': '<rootDir>/src/ComparePoint.ts',
    '^\\.\\./src/ComparePoint\\.js$': '<rootDir>/src/ComparePoint.ts',
    '^\\./Description\\.js$': '<rootDir>/src/Description.ts',
    '^\\.\\./Description\\.js$': '<rootDir>/src/Description.ts',
    '^\\.\\./\\.\\./Description\\.js$': '<rootDir>/src/Description.ts',
    '^\\.\\./\\.\\./src/Description\\.js$': '<rootDir>/src/Description.ts',
    '^\\.\\./src/Description\\.js$': '<rootDir>/src/Description.ts',
    '^\\./(CompareOperatorError|DataFormatError|DieActionValueError|NotationError|RequiredArgumentError)\\.js$': '<rootDir>/src/exceptions/$1.ts',
    '^\\./exceptions/(.*)\\.js$': '<rootDir>/src/exceptions/$1.ts',
    '^\\.\\./exceptions/(.*)\\.js$': '<rootDir>/src/exceptions/$1.ts',
    '^\\.\\./\\.\\./src/exceptions/(.*)\\.js$': '<rootDir>/src/exceptions/$1.ts',
    '^\\.\\./src/exceptions/(.*)\\.js$': '<rootDir>/src/exceptions/$1.ts',
    '^\\./traits/HasDescription\\.js$': '<rootDir>/src/traits/HasDescription.ts',
    '^\\.\\./traits/HasDescription\\.js$': '<rootDir>/src/traits/HasDescription.ts',
    '^\\.\\./\\.\\./src/traits/HasDescription\\.js$': '<rootDir>/src/traits/HasDescription.ts',
    '^\\./utilities/(ExportFormats|NumberGenerator|math|utils)\\.js$': '<rootDir>/src/utilities/$1.ts',
    '^\\.\\./utilities/(ExportFormats|NumberGenerator|math|utils)\\.js$': '<rootDir>/src/utilities/$1.ts',
    '^\\.\\./src/utilities/(ExportFormats|NumberGenerator|math|utils)\\.js$': '<rootDir>/src/utilities/$1.ts',
    '^\\.\\./\\.\\./utilities/(ExportFormats|NumberGenerator|math|utils)\\.js$': '<rootDir>/src/utilities/$1.ts',
    '^\\.\\./\\.\\./src/utilities/(ExportFormats|NumberGenerator|math|utils)\\.js$': '<rootDir>/src/utilities/$1.ts',
    '^\\./results/(.*)\\.js$': '<rootDir>/src/results/$1.ts',
    '^\\.\\./results/(.*)\\.js$': '<rootDir>/src/results/$1.ts',
    '^\\./ResultGroup\\.js$': '<rootDir>/src/results/ResultGroup.ts',
    '^\\./RollResult\\.js$': '<rootDir>/src/results/RollResult.ts',
    '^\\./RollResults\\.js$': '<rootDir>/src/results/RollResults.ts',
    '^\\.\\./\\.\\./src/results/(.*)\\.js$': '<rootDir>/src/results/$1.ts',
    '^\\.\\./src/results/(.*)\\.js$': '<rootDir>/src/results/$1.ts',
  },
  testMatch: [
    '<rootDir>/tests/**/*.[jt]s?(x)',
  ],
};
