package dicecore

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

// Fixtures are generated by the TypeScript reference, not by the Go port.
func loadFixtureCases(t *testing.T, filename string) []json.RawMessage {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("testdata", filename))
	if err != nil {
		t.Fatal(err)
	}
	var fixture struct {
		SchemaVersion int               `json:"schemaVersion"`
		Cases         []json.RawMessage `json:"cases"`
	}
	if err := json.Unmarshal(data, &fixture); err != nil {
		t.Fatal(err)
	}
	if fixture.SchemaVersion != 1 || len(fixture.Cases) == 0 {
		t.Fatalf("invalid or empty fixture: %s", filename)
	}
	return fixture.Cases
}

func assertFixtureOutcome(t *testing.T, expected json.RawMessage, value any, err error) {
	t.Helper()
	var outcome struct {
		Value json.RawMessage            `json:"value"`
		Error map[string]json.RawMessage `json:"error"`
	}
	if decodeErr := json.Unmarshal(expected, &outcome); decodeErr != nil {
		t.Fatal(decodeErr)
	}
	if outcome.Error != nil {
		if err == nil {
			t.Fatalf("expected error %s; got value %#v", expected, value)
		}
		actual := map[string]any{"message": err.Error()}
		var diceErr *DiceRollError
		if errors.As(err, &diceErr) {
			data, marshalErr := json.Marshal(diceErr)
			if marshalErr != nil {
				t.Fatal(marshalErr)
			}
			if decodeErr := json.Unmarshal(data, &actual); decodeErr != nil {
				t.Fatal(decodeErr)
			}
		}
		for field, raw := range outcome.Error {
			// Native errors do not have JS constructor names such as RangeError.
			if field == "name" && diceErr == nil {
				continue
			}
			var wanted any
			if decodeErr := json.Unmarshal(raw, &wanted); decodeErr != nil {
				t.Fatal(decodeErr)
			}
			if !reflect.DeepEqual(actual[field], wanted) {
				t.Errorf("error field %s: got %#v, want %#v", field, actual[field], wanted)
			}
		}
		return
	}
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(outcome.Value) == 0 {
		t.Fatal("fixture has neither value nor error")
	}
	actualBytes, marshalErr := json.Marshal(value)
	if marshalErr != nil {
		t.Fatal(marshalErr)
	}
	var actual, wanted any
	if decodeErr := json.Unmarshal(actualBytes, &actual); decodeErr != nil {
		t.Fatal(decodeErr)
	}
	if decodeErr := json.Unmarshal(outcome.Value, &wanted); decodeErr != nil {
		t.Fatal(decodeErr)
	}
	if !reflect.DeepEqual(actual, wanted) {
		t.Errorf("Go output differs from TypeScript\ngot  %s\nwant %s", actualBytes, outcome.Value)
	}
}
